import type { Theme } from './types';

export const classicThemes: Theme[] = [
  {
    id: 'apple',
    name: 'Mac',
    description: '纯净现代的极致留白，适合日常记录的万能首选',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1d1d1f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #1d1d1f !important;',
      strong: 'font-weight: 700; color: #000 !important; ',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #1d1d1f !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f5f5f7 !important; border-left: 4px solid #0066cc; color: #555 !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f5f5f7 !important; color: #0066cc !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f7 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1d1d1f !important; border: 1px solid #e0e0e0;',
      td: 'padding: 12px 16px; border: 1px solid #e0e0e0; color: #1d1d1f !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'claude',
    name: 'Claude',
    description: '温润的燕麦卡其色底，适合深度长文或文学哲思',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2b2b2b !important; background-color: #f8f6f0 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #b75c3d !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #b75c3d !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #2b2b2b !important;',
      strong: 'font-weight: 700; color: #b75c3d !important; background-color: rgba(183,92,61,0.08); padding:0 4px; border-radius:4px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #b75c3d !important; text-decoration: none; border-bottom: 1px solid #b75c3d; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #2b2b2b !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: rgba(183, 92, 61, 0.04) !important; border-left: 4px solid #b75c3d; color: #555 !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0ece4 !important; color: #b75c3d !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0ece4 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0ece4 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2b2b2b !important; border: 1px solid #e0ddd6;',
      td: 'padding: 12px 16px; border: 1px solid #e0ddd6; color: #2b2b2b !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'wechat',
    name: '微信公众号原生',
    description: '原汁原味的官方绿底纹，满足传统阅读习惯的稳妥之选',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #333333 !important;',
      strong: 'font-weight: 700; color: #07c160 !important; background-color: rgba(7,193,96,0.08); padding: 0 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #07c160 !important; text-decoration: none; border-bottom: 1px solid #07c160; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #333333 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f0f7f2 !important; border-left: 4px solid #07c160; color: #555 !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0f7f2 !important; color: #07c160 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0f7f2 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0f7f2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333333 !important; border: 1px solid #d8e8dc;',
      td: 'padding: 12px 16px; border: 1px solid #d8e8dc; color: #333333 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'media',
    name: 'NYT',
    description: '经典米黄色新闻纸，极强的严肃深度报道专业感',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #000000 !important; background-color: #fdfaf6 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; border-bottom: 2px solid #000; padding-bottom:12px;',
      h2: 'font-size: 26px; font-weight: 700; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #000000 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #000000 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #000000 !important;',
      strong: 'font-weight: 700; color: #000 !important; ',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #326891 !important; text-decoration: none; border-bottom: 1px solid #326891; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #000000 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f0ede8 !important; border-left: 4px solid #326891; color: #555 !important; border-radius: 4px; font-style: italic;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0ede8 !important; color: #326891 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0ede8 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #d5cfc5 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0ede8 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #000000 !important; border: 1px solid #d5cfc5;',
      td: 'padding: 12px 16px; border: 1px solid #d5cfc5; color: #000000 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'medium',
    name: 'Medium',
    description: '简约柔和的西式博客排版，适合生活志与随笔沉淀',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.85 !important; color: #242424 !important; background-color: #fcfcfc !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #242424 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #242424 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 24px 0 !important; line-height: 1.85 !important; color: #242424 !important;',
      strong: 'font-weight: 700; color: #000 !important; ',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #1a8917 !important; text-decoration: none; border-bottom: 1px solid #1a8917; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 10px 0; line-height: 1.85 !important; color: #242424 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: transparent !important; border-left: 3px solid #1a8917; color: #555 !important; border-radius: 0; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f2f3f5 !important; color: #1a8917 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f2f3f5 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f2f3f5 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #242424 !important; border: 1px solid #e0e0e0;',
      td: 'padding: 12px 16px; border: 1px solid #e0e0e0; color: #242424 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: '前沿的硅谷极客商务风，高悬浮感与高亮视觉系',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #425466 !important; background-color: #f6f9fc !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #425466 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #425466 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #425466 !important;',
      strong: 'font-weight: 700; color: #0a2540 !important; ',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #635bff !important; text-decoration: none; border-bottom: 1px solid #635bff; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #425466 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #eef0ff !important; border-left: 4px solid #635bff; color: #425466 !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0f2fe !important; color: #635bff !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0f2fe !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #e0e0e0 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0f2fe !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #425466 !important; border: 1px solid #dde0f0;',
      td: 'padding: 12px 16px; border: 1px solid #dde0f0; color: #425466 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'workspace',
    name: '飞书效率',
    description: '1:1 还原飞书文档排版，基于 Semi Design 设计规范',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6 !important; color: #1c1f23 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 600; color: #1c1f23 !important; line-height: 1.375 !important; margin: 26px 0 10px;',
      h2: 'font-size: 28px; font-weight: 600; color: #1c1f23 !important; line-height: 1.4 !important; margin: 22px 0 10px;',
      h3: 'font-size: 24px; font-weight: 600; color: #1c1f23 !important; line-height: 1.4 !important; margin: 20px 0 8px;',
      h4: 'font-size: 20px; font-weight: 600; color: #1c1f23 !important; line-height: 1.4 !important; margin: 18px 0 8px;',
      p: 'margin: 8px 0 !important; line-height: 1.6 !important; color: #1c1f23 !important;',
      strong: 'font-weight: 600; color: #1c1f23 !important;',
      em: 'font-style: italic; color: rgba(28, 31, 35, 0.8) !important;',
      a: 'color: #0064fa !important; text-decoration: none; border-bottom: 1px solid rgba(0, 100, 250, 0.3); padding-bottom: 1px;',
      ul: 'margin: 8px 0; padding-left: 24px;',
      ol: 'margin: 8px 0; padding-left: 24px;',
      li: 'margin: 4px 0; line-height: 1.6 !important; color: #1c1f23 !important;',
      blockquote: 'margin: 12px 0; padding: 12px 16px; background-color: rgba(46, 50, 56, 0.05) !important; border-left: 3px solid #e6e8ea; color: rgba(28, 31, 35, 0.8) !important; border-radius: 3px;',
      code: 'font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; padding: 2px 6px; background-color: rgba(46, 50, 56, 0.05) !important; color: #1c1f23 !important; border-radius: 3px; font-size: 12px !important; line-height: 1.5 !important; border: 1px solid rgba(28, 31, 35, 0.08);',
      pre: 'margin: 12px 0; padding: 16px; background-color: rgba(46, 50, 56, 0.05) !important; border-radius: 6px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important; border: 1px solid rgba(28, 31, 35, 0.08);',
      hr: 'margin: 24px auto; border: none; height: 1px; background-color: rgba(28, 31, 35, 0.08) !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 6px;',
      table: 'width: 100%; margin: 12px 0; border-collapse: collapse; font-size: 14px;',
      th: 'background-color: rgba(46, 50, 56, 0.05) !important; padding: 8px 16px; text-align: left; font-weight: 600; color: #1c1f23 !important; border: 1px solid rgba(28, 31, 35, 0.08);',
      td: 'padding: 8px 16px; border: 1px solid rgba(28, 31, 35, 0.08); color: #1c1f23 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'linear',
    name: 'Linear',
    description: '纯正的暗夜赛博极客风，编程教程与开发日志的终极归宿',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f1f1f2 !important; background-color: #101114 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #f1f1f2 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #f1f1f2 !important;',
      strong: 'font-weight: 700; color: #fff !important; ',
      em: 'font-style: italic; color: #bbb !important;',
      a: 'color: #5e6ad2 !important; text-decoration: none; border-bottom: 1px solid #5e6ad2; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #f1f1f2 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #1a1a1a !important; border-left: 4px solid #5e6ad2; color: #ccc !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #1a1a2e !important; color: #5e6ad2 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1a1a2e !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #1a1a2e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #f1f1f2 !important; border: 1px solid #333;',
      td: 'padding: 12px 16px; border: 1px solid #333; color: #f1f1f2 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'retro',
    name: 'Retro',
    description: '做旧羊皮纸搭配火漆红，适合人文历史与艺术鉴赏',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #2b2621 !important; background-color: #f4ecd8 !important; background-image: radial-gradient(circle at center, #f4ecd8 0%, #ebdec4 100%); word-wrap: break-word;',
      h1: 'font-size: 36px; font-weight: 800; color: #2b2621 !important; line-height: 1.2 !important; margin: 38px 0 20px; letter-spacing: -0.02em; font-variant: small-caps;',
      h2: 'font-size: 26px; font-weight: 700; color: #8c2211 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #2b2621 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #2b2621 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #2b2621 !important;',
      strong: 'font-weight: 700; color: #8c2211 !important; ',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #8c2211 !important; text-decoration: none; border-bottom: 1px solid #8c2211; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #2b2621 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #efe5cc !important; border-left: 4px solid #8c2211; color: #555 !important; border-radius: 4px; font-style: italic;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #ede4d0 !important; color: #8c2211 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #ede4d0 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #d4c9ae !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #ede4d0 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2b2621 !important; border: 1px solid #d4c9ae;',
      td: 'padding: 12px 16px; border: 1px solid #d4c9ae; color: #2b2621 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg',
    description: '还原华尔街古老金融终端机，硬派科技代码展示专属',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: "SF Mono", "Courier New", Courier, monospace; font-size: 16px; line-height: 1.7 !important; color: #15fa52 !important; background-color: #000000 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #15fa52 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #15fa52 !important;',
      strong: 'font-weight: 700; color: #15fa52 !important; ',
      em: 'font-style: italic; color: #bbb !important;',
      a: 'color: #ff8c00 !important; text-decoration: none; border-bottom: 1px solid #ff8c00; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #15fa52 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #0a0a0a !important; border: 1px solid #333; color: #ccc !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #0a0a0a !important; color: #ff8c00 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #0a0a0a !important; border: 1px solid #333; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #0a0a0a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #15fa52 !important; border: 1px solid #333;',
      td: 'padding: 12px 16px; border: 1px solid #333; color: #15fa52 !important;',
      tr: 'border: none;',
    }
  },
];
